# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('filial', models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Paraiba', 'Paraiba')], max_length=30)),
                ('vinculo', models.CharField(choices=[('Em Serviço', 'Em Serviço'), ('Dispensado', 'Dispensado')], max_length=20)),
                ('cargo', models.CharField(choices=[('Desenvolvedor', 'Desenvolvedor'), ('DEV', 'DEV'), ('Advogado', 'Advogado'), ('Contador', 'Contador')], max_length=20)),
                ('mae', models.CharField(max_length=150)),
                ('pai', models.CharField(max_length=150)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Viuvo', 'Viuvo')], max_length=30)),
                ('laudo', models.TextField()),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
