# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Perfil',
        ),
    ]
